"""initial database schema

Revision ID: 6610f4eca32c
Revises: 3e2ea981aa19
Create Date: 2026-09-23 00:25:15.688715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6610f4eca32c'
down_revision = '3e2ea981aa19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
